name: Deploy to AWS EKS - CD

on:
  push:
    branches: [ "main" ]

env:
  # AWS Bucket Keys
  ACCESS_KEY_BUCKET: ${{ secrets.ACCESS_KEY_BUCKET }}
  SECRET_KEY_BUCKET: ${{ secrets.SECRET_KEY_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: generate image tag
      id: image-tag
      run: echo "::set-output name=IMAGE_TAG::$(date '+%d.%m.%Y.%H.%M.%S')"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}




    - name: install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.5'
      id: install-kubectl

    - name: setup aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_BUCKET }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY_BUCKET }}
        aws-region: us-east-1

    - name: update kube config
      run: aws eks update-kubeconfig --name demo-microservices --region us-east-1

    - name: deploy to AWS EKS
      run: |
        kubectl apply -f 01-MySQL-externalName-Service.yml
        kubectl apply -f 02-UserManagementMicroservice-Deployment.yml
        kubectl apply -f 03-UserManagement-NodePort-Service.yml
        kubectl apply -f 04-NotificationMicroservice-Deployment.yml
        kubectl apply -f 05-NotificationMicroservice-SMTP-externalName-Service.yml
        kubectl apply -f 06-NotificationMicroservice-ClusterIP-Service.yml
        kubectl apply -f 07-ALB-Ingress-SSL-Redirect-ExternalDNS.yml
